export const LONDON_WEATHER_PALETTES = [
  {
    id: 'riverMist',
    slug: 'river-mist',
    label: 'Signal Rain',
    weather: 'Rain Front',
    personality: 'Wet, charged, humane.',
    story:
      'Rain turns the city into a live interface: soaked pavement, bus glass, crosswalk reflections, and one neon-citrus note cutting through the grey. The warmth comes from windows and people, not nostalgia.',
    words: [
      'wet signal',
      'bus glass',
      'crosswalk glare',
      'umbrella black',
      'window amber',
      'transit blue',
      'river skin',
      'late kindness',
      'station light',
      'soft asphalt',
      'phone glow',
      'rain code',
    ],
    light: ['#a7afb0', '#c6cecf', '#f5f8f6', '#00a5a0', '#031210', '#d7ff2f', '#2c96ff', '#ff7e4a'],
    dark: ['#a7afb0', '#c6cecf', '#f5f8f6', '#00a5a0', '#031210', '#d7ff2f', '#2c96ff', '#ff7e4a'],
    screenshot: '/images/palette-review/river-mist.png',
    theme: {
      bgLight: '#eef4f2',
      bgDark: '#061816',
      wallBaseLight: '#edf4f1',
      wallBaseDark: '#061816',
      quoteButtonColorLight: '#edf4f1',
      quoteButtonColorDark: '#061816',
      frameColorLight: '#081715',
      frameColorDark: '#081715',
      siteFrameLight: '#081715',
      siteFrameDark: '#081715',
      safariFrameLight: '#031210',
      safariFrameDark: '#031210',
      lockedHeaderLight: '#081715',
      lockedHeaderDark: '#081715',
      textColorLight: '#091311',
      textColorLightMuted: '#32504a',
      textColorDark: '#eef8f4',
      textColorDarkMuted: '#9ec5bd',
      linkHoverColor: '#d7ff2f',
      colorAccent: '#ff7e4a',
      heroRoleAccent: '#ff7e4a',
      noiseColorLight: '#21413c',
      noiseColorDark: '#8ec4b8',
      depthWashCenterColorLight: '#f5f8f6',
      depthWashEdgeColorLight: '#0f4352',
      depthWashCenterColorDark: '#04110f',
      depthWashEdgeColorDark: '#0a252c',
      absFgPrimaryLight: '#091311',
      absFgPrimaryDark: '#eef8f4',
      absFgSecondaryLight: '#32504a',
      absFgSecondaryDark: '#9ec5bd',
      absFgMutedLight: '#4f6d67',
      absFgMutedDark: '#7fa8a0',
      panelBrand: '#ff7e4a',
    },
  },
  {
    id: 'portlandHaze',
    slug: 'portland-haze',
    label: 'High Cloud',
    weather: 'Bright Overcast',
    personality: 'Exact parity with the original runtime.',
    story:
      'This is the original system untouched: the balanced industrial teal chapter that held the site together before we started changing anything. It stays here as the control specimen.',
    words: [
      'original',
      'industrial teal',
      'control',
      'default',
      'teal chapter',
      'amber note',
      'signal red',
      'cobalt accent',
      'familiar',
      'baseline',
      'parity',
      'as-was',
    ],
    light: ['#b5b7b6', '#bbbdbd', '#ffffff', '#00695c', '#000000', '#f03030', '#0d5cb6', '#ffa000'],
    dark: ['#b5b7b6', '#bbbdbd', '#ffffff', '#00695c', '#000000', '#f03030', '#0d5cb6', '#ffa000'],
    screenshot: '/images/palette-review/portland-haze.png',
    theme: {
      bgLight: '#efefef',
      bgDark: '#181818',
      wallBaseLight: '#efefef',
      wallBaseDark: '#181818',
      quoteButtonColorLight: '#efefef',
      quoteButtonColorDark: '#181818',
      frameColorLight: '#242529',
      frameColorDark: '#242529',
      siteFrameLight: '#202124',
      siteFrameDark: '#202124',
      safariFrameLight: '#181818',
      safariFrameDark: '#181818',
      lockedHeaderLight: '#f1f3f4',
      lockedHeaderDark: '#3c3c3c',
      textColorLight: '#161616',
      textColorLightMuted: '#2f2f2f',
      textColorDark: '#f0f0f0',
      textColorDarkMuted: '#c8c8c8',
      linkHoverColor: '#f03030',
      colorAccent: '#f03030',
      heroRoleAccent: '#e10600',
      noiseColorLight: '#2a2a2e',
      noiseColorDark: '#d4d4d8',
      depthWashCenterColorLight: '#ffffff',
      depthWashEdgeColorLight: '#142b48',
      depthWashCenterColorDark: '#1a1e23',
      depthWashEdgeColorDark: '#05020f',
      absFgPrimaryLight: '#161616',
      absFgPrimaryDark: '#f0f0f0',
      absFgSecondaryLight: '#2f2f2f',
      absFgSecondaryDark: '#c8c8c8',
      absFgMutedLight: '#454545',
      absFgMutedDark: '#a8a8a8',
      panelBrand: '#ffa000',
    },
  },
  {
    id: 'blueBreak',
    slug: 'blue-break',
    label: 'Blue Break',
    weather: 'Sun Between Showers',
    personality: 'Spring light, open and electric.',
    story:
      'Sun breaks through after rain and London suddenly feels lighter, faster, more future-facing. This one pushes the optimistic end of the system: hard cobalt, clean sky, warm signal orange, and one acid-citrus spark.',
    words: [
      'cobalt break',
      'after-rain light',
      'river flash',
      'sun on glass',
      'signal orange',
      'warm metal',
      'lift',
      'clear edge',
      'open sky',
      'spring pulse',
      'studio window',
      'fast air',
    ],
    light: ['#b6bcc0', '#dbe3e6', '#fffdf6', '#1768ff', '#07111b', '#ff6a00', '#53b9ff', '#d8ff38'],
    dark: ['#b6bcc0', '#dbe3e6', '#fffdf6', '#1768ff', '#07111b', '#ff6a00', '#53b9ff', '#d8ff38'],
    screenshot: '/images/palette-review/blue-break.png',
    theme: {
      bgLight: '#edf6ff',
      bgDark: '#081526',
      wallBaseLight: '#ecf6ff',
      wallBaseDark: '#081526',
      quoteButtonColorLight: '#ecf6ff',
      quoteButtonColorDark: '#081526',
      frameColorLight: '#0c1a31',
      frameColorDark: '#0c1a31',
      siteFrameLight: '#0c1a31',
      siteFrameDark: '#0c1a31',
      safariFrameLight: '#07111b',
      safariFrameDark: '#07111b',
      lockedHeaderLight: '#dfeafb',
      lockedHeaderDark: '#0c1a31',
      textColorLight: '#081220',
      textColorLightMuted: '#365884',
      textColorDark: '#f6fbff',
      textColorDarkMuted: '#aec7ea',
      linkHoverColor: '#ff6a00',
      colorAccent: '#1768ff',
      heroRoleAccent: '#1768ff',
      noiseColorLight: '#2b4b74',
      noiseColorDark: '#a7d5ff',
      depthWashCenterColorLight: '#ffffff',
      depthWashEdgeColorLight: '#1a5bcf',
      depthWashCenterColorDark: '#07111b',
      depthWashEdgeColorDark: '#0b2554',
      absFgPrimaryLight: '#081220',
      absFgPrimaryDark: '#f6fbff',
      absFgSecondaryLight: '#365884',
      absFgSecondaryDark: '#aec7ea',
      absFgMutedLight: '#5f7eaa',
      absFgMutedDark: '#84a8d6',
      panelBrand: '#1768ff',
    },
  },
  {
    id: 'sodiumRain',
    slug: 'sodium-rain',
    label: 'Heat Veil',
    weather: 'Heat Haze',
    personality: 'Sulfur-lit, ultraviolet, suspended.',
    story:
      'The air goes thick and bright before summer rain arrives. Pavement lightens, edges shimmer, and colour feels slightly unreal: ultraviolet bruising into chartreuse, with hot metal orange holding the human temperature in the frame.',
    words: [
      'heat shimmer',
      'humid glass',
      'soft voltage',
      'warm concrete',
      'monitor bruise',
      'tube heat',
      'sulfur flash',
      'plum air',
      'held breath',
      'haze line',
      'quiet static',
      'summer build',
    ],
    light: ['#aca1ab', '#d8cdd2', '#fbf0e8', '#8a52ff', '#18081a', '#ff7a12', '#dfff2a', '#88efff'],
    dark: ['#aca1ab', '#d8cdd2', '#fbf0e8', '#8a52ff', '#18081a', '#ff7a12', '#dfff2a', '#88efff'],
    screenshot: '/images/palette-review/sodium-rain.png',
    theme: {
      bgLight: '#fbf0e8',
      bgDark: '#18081a',
      wallBaseLight: '#fbf0e8',
      wallBaseDark: '#18081a',
      quoteButtonColorLight: '#fbf0e8',
      quoteButtonColorDark: '#18081a',
      frameColorLight: '#250e27',
      frameColorDark: '#250e27',
      siteFrameLight: '#250e27',
      siteFrameDark: '#250e27',
      safariFrameLight: '#18081a',
      safariFrameDark: '#18081a',
      lockedHeaderLight: '#f0e1eb',
      lockedHeaderDark: '#250e27',
      textColorLight: '#1d0c17',
      textColorLightMuted: '#6a475d',
      textColorDark: '#fff3fb',
      textColorDarkMuted: '#d6b4ca',
      linkHoverColor: '#ff7a12',
      colorAccent: '#8a52ff',
      heroRoleAccent: '#dfff2a',
      noiseColorLight: '#5b324f',
      noiseColorDark: '#efcbe0',
      depthWashCenterColorLight: '#fff4ee',
      depthWashEdgeColorLight: '#8336a6',
      depthWashCenterColorDark: '#18081a',
      depthWashEdgeColorDark: '#2b0f30',
      absFgPrimaryLight: '#1d0c17',
      absFgPrimaryDark: '#fff3fb',
      absFgSecondaryLight: '#6a475d',
      absFgSecondaryDark: '#d6b4ca',
      absFgMutedLight: '#8a647a',
      absFgMutedDark: '#bc90ac',
      panelBrand: '#dfff2a',
    },
  },
];

export const DEFAULT_LONDON_WEATHER_PALETTE_ID = LONDON_WEATHER_PALETTES[0].id;

export const LONDON_WEATHER_PALETTE_MAP = Object.freeze(
  LONDON_WEATHER_PALETTES.reduce((acc, palette) => {
    acc[palette.id] = palette;
    return acc;
  }, {})
);

export function resolveLondonWeatherPaletteId(value) {
  const raw = String(value || '').trim();
  if (!raw) return null;
  const byId = LONDON_WEATHER_PALETTE_MAP[raw];
  if (byId) return byId.id;
  const bySlug = LONDON_WEATHER_PALETTES.find((palette) => palette.slug === raw);
  return bySlug ? bySlug.id : null;
}

export function getLondonWeatherPalette(paletteId) {
  const resolvedId = resolveLondonWeatherPaletteId(paletteId) || DEFAULT_LONDON_WEATHER_PALETTE_ID;
  return LONDON_WEATHER_PALETTE_MAP[resolvedId];
}

export function getLondonWeatherPaletteTheme(paletteId) {
  return getLondonWeatherPalette(paletteId)?.theme || null;
}
